### ISSUE TITLE
findAndConnect returns FALSE in android 10

### ISSUE THREAD

**Issue by krishnaaro** [weplenish/flutter-plugins#11]
after android Q update, can't able to connect through findAndConnect function. no error log occurred too. please let me know if I'm missing something .... !

**Comment by vipero07** [comment]
There is no find and connect function related to any of these libraries. However, your issue is likely related to the inability to scan for wifi networks nearby since android R. The ability to start a scan using the wifimanager was deprecated and would prevent initiating a network scan.
