### ISSUE TITLE
Rssi Refreshing rate?

### ISSUE THREAD

**Issue by zeeshan0309** [weplenish/flutter-plugins#12]
How long does it take to actually reload/update new rssi values? I tested the sample code on my mobile, but it takes more than 3 minutes to update the rssi values

**Comment by vipero07** [comment]
Unfortunately the updates are left up to Android OS. For battery conservation and security reasons calling startscan in android is throttled. Each different android version has unique throttling to make matters worse.

- Android 8.0 and 8.1 are throttled to once every 30 minutes
- Android 9 allows 4 calls in a 2 minute burst for foreground applications, and once every 30 minutes for background apps.
- Android 10 and higher is the same as 9 but has dev options to change the throttling for local development (which would obviously not apply to application users)

For more information see: [Wifi Scan Throttling](https://developer.android.com/guide/topics/connectivity/wifi-scan#wifi-scan-throttling)

This also is unique to wifi scanning, not explicitly RSSI updates, I imagine its possible the RSSI values may not even update upon receiving a new wifi scan result but that is lower level kernel stuff that devs don't have access to.
