### ISSUE TITLE
[ERROR] PlatformException(startScan, Unable to start scan., false, null)

### ISSUE THREAD

**Issue by zeeshan0309** [weplenish/flutter-plugins#13]
I'm using this "wifi_flutter" plugin in an app of mine. Basically I am calling the "scanNetworks()" to get a list of available networks, but its unable to scan for some reason. I've encountered this error while debugging:

E/flutter (12176): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: PlatformException(startScan, Unable to start scan., false, null)

E/flutter (12176): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)

E/flutter (12176): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)

E/flutter (12176): <asynchronous suspension>

E/flutter (12176): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)

E/flutter (12176): #3      WifiFlutter.scanNetworks (package:wifi_flutter/wifi_flutter.dart:26:37)

E/flutter (12176): #4      _MyAppState.initState.<anonymous closure> (package:hope_falling/frontpage.dart:34:42)

E/flutter (12176): <asynchronous suspension>

E/flutter (12176): #5      _MyAppState.initState.<anonymous closure> (package:hope_falling/frontpage.dart)

E/flutter (12176): #6      _rootRunUnary (dart:async/zone.dart:1198:47)

E/flutter (12176): #7      _CustomZone.runUnary (dart:async/zone.dart:1100:19)

E/flutter (12176): #8      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)

E/flutter (12176): #9      _CustomZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1042:26)

E/flutter (12176): #10     _rootRunUnary (dart:async/zone.dart:1206:13)

E/flutter (12176): #11     _CustomZone.runUnary (dart:async/zone.dart:1100:19)

E/flutter (12176): #12     _CustomZone.bindUnaryCallback.<anonymous closure> (dart:async/zone.dart:1026:26)

E/flutter (12176): #13     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)

E/flutter (12176): #14     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)

E/flutter (12176): #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

My initial guess was that this issue is due to some Permission denial stuff, so I added these in my  AndroidManifest.xml file:

"uses-permission android:name="android.permission.ACCESS_WIFI_STATE" 
uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" 
uses-permission android:name="android.permission.CHANGE_WIFI_STATE" 
uses-permission android:name="android.hardware.wifi" 
uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" 
uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" 
uses-permission android:name="android.permission.INTERNET" "

but this too didnt change anything. I am calling WifiFlutter.scanNetworks() like this:

```
   @override void initState(){
    super.initState();
    Timer.periodic(Duration(seconds: 7), (timer) async{
      final noPermissions = await WifiFlutter.promptPermissions();
      if(noPermissions){
        return;
      }
      final networks = await WifiFlutter.scanNetworks();
      if(this.mounted) {
        setState(() {
          _platformVersion = networks
              .map((network) =>
              Text(
                  "${network.ssid} ${network.rssi}"))
              .toList();
          records =
              _platformVersion.map((element) => getString(element)).toList();
          Signal processedList = processingRec(records);
          createRecord(processedList);
          //sleep(const Duration(seconds: 7));
          getRecord();
          print(records);
          print(test);
        });
      }
    });
  }```


please let me know what could possibly be causing this, and what should I do to get it to work properly

**Comment by vipero07** [comment]
You are correct in needing the permissions but you also need to request them in code before attempting any of the connection stuff. I suggest something like https://pub.dev/packages/permission_handler a good example of implementation can be found here https://stackoverflow.com/a/58680215.

The permission handling was intentionally left out of this plugin (instead of forcing it on users) since it isn't likely the only use case for certain permissions and there are plenty of flutter packages that handle permissions alone.

**Comment by vipero07** [comment]
I'm going to try and remember to add that to the usage documentation.

**Comment by vipero07** [comment]
Depending on your use case though https://github.com/weplenish/flutter_wifi_connect may be a better fit.

**Comment by shubhamdarekar** [comment]
Facing the same issue cannot solve it
